require 'test/test-primitives'
require 'test/test-array'
require 'test/test-dynarray'
require 'test/test-nesting'
require 'test/test-simple-properties'
require 'test/types/test-integer'
require 'test/types/test-string'
require 'test/types/test-cstring'
